// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cromosmundial_proyecto_final.Data;

#nullable disable

namespace cromosmundial_proyecto_final.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cromosmundial_proyecto_final.Models.Cromo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JugadorId")
                        .HasColumnType("int");

                    b.Property<int>("MundialId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroCamiseta")
                        .HasColumnType("int");

                    b.Property<string>("Posicion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaFoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeleccionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.HasIndex("MundialId");

                    b.HasIndex("SeleccionId");

                    b.ToTable("Cromos");
                });

            modelBuilder.Entity("cromosmundial_proyecto_final.Models.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Historia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("cromosmundial_proyecto_final.Models.Mundial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisSede")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mundiales");
                });

            modelBuilder.Entity("cromosmundial_proyecto_final.Models.Seleccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Confederacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectorTecnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaFoto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Selecciones");
                });

            modelBuilder.Entity("cromosmundial_proyecto_final.Models.Cromo", b =>
                {
                    b.HasOne("cromosmundial_proyecto_final.Models.Jugador", "Jugador")
                        .WithMany("Cromos")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cromosmundial_proyecto_final.Models.Mundial", "Mundial")
                        .WithMany("Cromos")
                        .HasForeignKey("MundialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cromosmundial_proyecto_final.Models.Seleccion", "Seleccion")
                        .WithMany("Cromos")
                        .HasForeignKey("SeleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");

                    b.Navigation("Mundial");

                    b.Navigation("Seleccion");
                });

            modelBuilder.Entity("cromosmundial_proyecto_final.Models.Jugador", b =>
                {
                    b.Navigation("Cromos");
                });

            modelBuilder.Entity("cromosmundial_proyecto_final.Models.Mundial", b =>
                {
                    b.Navigation("Cromos");
                });

            modelBuilder.Entity("cromosmundial_proyecto_final.Models.Seleccion", b =>
                {
                    b.Navigation("Cromos");
                });
#pragma warning restore 612, 618
        }
    }
}
